services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
    public: true

  LotteryBundle\Command\:
    resource: '../../Command/'
  LotteryBundle\Controller\:
    resource: '../../Controller/'
  LotteryBundle\DataFixtures\:
    resource: '../../DataFixtures/'
  LotteryBundle\EventSubscriber\:
    resource: '../../EventSubscriber/'
  LotteryBundle\ExpressionLanguage\:
    resource: '../../ExpressionLanguage/'
  LotteryBundle\MessageHandler\:
    resource: '../../MessageHandler/'
  LotteryBundle\Procedure\:
    resource: '../../Procedure/'
  LotteryBundle\Repository\:
    resource: '../../Repository/'
  LotteryBundle\Service\:
    resource: '../../Service/'
